const cars = [
    {
      id: 1,
    //   imageUrl: "./assets/89824770.png",
      imageUrl: "https://res.cloudinary.com/dr1pmtefx/image/upload/f_auto,q_auto/89824770_vi5qxq",
    //   imageUrl: "https://cdni.autocarindia.com/utils/imageresizer.ashx?n=https://cms.haymarketindia.net/model/uploads/modelimages/Hyundai-Grand-i10-Nios-200120231541.jpg",
      name: "Renault Kwid",
      price: 49,
      fuelType: 'Petrol',
      transmissionType: 'Manual',
      numSeats: '5',
      category: "Hatchback",
      imageHeight: 200,
    },
    {
      id: 2,
      imageUrl: "https://res.cloudinary.com/dr1pmtefx/image/upload/f_auto,q_auto/s-presso_range_bknjxb",
    //   imageUrl: "https://cdni.autocarindia.com/utils/imageresizer.ashx?n=https://cms.haymarketindia.net/model/uploads/modelimages/Hyundai-Grand-i10-Nios-200120231541.jpg",
      name: "Maruti Suzuzki S-presso",
      price: 59,
      fuelType: 'Petrol',
      transmissionType: 'Manual',
      numSeats: '5',
      category: "Hatchback",
      imageHeight: 200,
    },
    {
      id: 3,
      imageUrl: "https://res.cloudinary.com/dr1pmtefx/image/upload/f_auto,q_auto/best-sedan-cars-in-india_qp9tnt",
    //   imageUrl: "https://cdni.autocarindia.com/utils/imageresizer.ashx?n=https://cms.haymarketindia.net/model/uploads/modelimages/Hyundai-Grand-i10-Nios-200120231541.jpg",
      name: "Honda City",
      price: 149,
      fuelType: 'Petrol',
      transmissionType: 'Manual',
      numSeats: '5',
      category: "Sedan",
      imageHeight: 200,
    },
    {
      id: 4,
      imageUrl: "https://res.cloudinary.com/dr1pmtefx/image/upload/f_auto,q_auto/1679903528_g1nhpt",
    //   imageUrl: "https://cdni.autocarindia.com/utils/imageresizer.ashx?n=https://cms.haymarketindia.net/model/uploads/modelimages/Hyundai-Grand-i10-Nios-200120231541.jpg",
      name: "Hyundai Verna",
      price: 199,
      fuelType: 'Petrol',
      transmissionType: 'Manual',
      numSeats: '5',
      category: "Sedan",
      imageHeight: 200,
    },
    {
      id: 5,
      imageUrl: "https://res.cloudinary.com/dr1pmtefx/image/upload/f_auto,q_auto/Brezza_side_img_qc9hkt",
      name: "Maruti Suzuki Brezza",
      price: 99,
      fuelType: 'Petrol',
      transmissionType: 'Manual',
      numSeats: '5',
      category: "SUV",
      imageHeight: 200,
    },
    {
      id: 6,
      imageUrl: "https://res.cloudinary.com/dr1pmtefx/image/upload/f_auto,q_auto/Overview_e0h9uu",
      name: "MG Hector",
      price: 249,
      fuelType: 'Diesel',
      transmissionType: 'Manual',
      numSeats: '7',
      category: "SUV",
      imageHeight: 200,
    },
    {
      id: 7,
      imageUrl: "https://res.cloudinary.com/dr1pmtefx/image/upload/f_auto,q_auto/best-muv-cars-in-india_oqoodl",
      name: "Maruti Suzuki Ertiga",
      price: 149,
      fuelType: 'Petrol',
      transmissionType: 'Manual',
      numSeats: '7',
      category: "MUV",
      imageHeight: 200,
    },
    {
      id: 8,
      imageUrl: "https://res.cloudinary.com/dr1pmtefx/image/upload/f_auto,q_auto/innova_becrq3",
      name: "Toyota Innova",
      price: 199,
      fuelType: 'Diesel',
      transmissionType: 'Manual',
      numSeats: '7',
      category: "MUV",
      imageHeight: 200,
    },
    {
      id: 9,
      imageUrl: "https://res.cloudinary.com/dr1pmtefx/image/upload/f_auto,q_auto/17733439-ScorpioN.jpg-804fbad4-929e-4acc-ac51-196a4b95f367_f2qt6p",
      name: "Mahindra Scorpio N",
      price: 249,
      fuelType: 'Diesel',
      transmissionType: 'Manual',
      numSeats: '7',
      category: "SUV",
      imageHeight: 200,
    },
    {
      id: 10,
      imageUrl: "https://res.cloudinary.com/dr1pmtefx/image/upload/f_auto,q_auto/2015-Suzuki-Swift-1.2-launched-in-Philippines_zgc5kj",
      name: "Maruti Suzuki Swift",
      price: 99,
      fuelType: 'Petrol',
      transmissionType: 'Manual',
      numSeats: '5',
      category: "Hatchback",
      imageHeight: 200,
    },
    {
      id: 11,
      imageUrl: "https://res.cloudinary.com/dr1pmtefx/image/upload/f_auto,q_auto/tata-nexon-ev-right-front-three-quarter6__1_-removebg-preview_atqcj5",
      name: "Tata Nexon EV",
      price: 199,
      fuelType: 'Electric',
      transmissionType: 'automatic',
      numSeats: '5',
      category: "SUV",
      imageHeight: 200,
    },
    {
      id: 12,
      imageUrl: "https://res.cloudinary.com/dr1pmtefx/image/upload/f_auto,q_auto/kia_seltos_rtimzk",
      name: "Kia Seltos",
      price: 199,
      fuelType: 'Diesel',
      transmissionType: 'Manual',
      numSeats: '5',
      category: "SUV",
      imageHeight: 200,
    },
  ];

export default cars